export interface AptitudeQuestion {
  id: string;
  category: 'Quantitative' | 'Logical Reasoning' | 'Verbal Ability';
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export interface CodingChallenge {
  id: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  category: string;
  description: string;
  inputFormat: string;
  outputFormat: string;
  sampleInput: string;
  sampleOutput: string;
  starterCode: {
    python: string;
    java: string;
    javascript: string;
  };
  solutionExplanation: string;
}

export interface InterviewQuestion {
  id: string;
  category: 'Technical' | 'HR' | 'System Design';
  topic: string;
  question: string;
  answerSummary: string;
  keyPoints: string[];
  commonMistakes: string[];
}

export const APTITUDE_QUESTIONS: AptitudeQuestion[] = [
  {
    id: 'apt-1',
    category: 'Quantitative',
    question: 'A train 240 m long passes a pole in 24 seconds. How long will it take to pass a platform 650 m long?',
    options: ['65 seconds', '89 seconds', '100 seconds', '150 seconds'],
    correctAnswer: 1,
    explanation: 'Speed of train = 240 / 24 = 10 m/s. Total distance to cross platform = 240 + 650 = 890 m. Time = 890 / 10 = 89 seconds.'
  },
  {
    id: 'apt-2',
    category: 'Quantitative',
    question: 'If the cost price of 12 pens is equal to the selling price of 8 pens, what is the gain percentage?',
    options: ['33.33%', '40%', '50%', '60%'],
    correctAnswer: 2,
    explanation: 'Let CP of 1 pen = Rs 1. CP of 8 pens = Rs 8. SP of 8 pens = CP of 12 pens = Rs 12. Gain = 12 - 8 = 4. Gain % = (4/8) * 100 = 50%.'
  },
  {
    id: 'apt-3',
    category: 'Logical Reasoning',
    question: 'Find the next number in sequence: 3, 7, 15, 31, 63, ?',
    options: ['95', '127', '128', '144'],
    correctAnswer: 1,
    explanation: 'Each term is generated by (Term * 2) + 1. 63 * 2 + 1 = 127.'
  },
  {
    id: 'apt-4',
    category: 'Verbal Ability',
    question: 'Choose the word most opposite in meaning (Antonym) to "CANDID":',
    options: ['Frank', 'Deceitful', 'Blunt', 'Honest'],
    correctAnswer: 1,
    explanation: 'Candid means truthful and straightforward. The opposite is deceitful or secretive.'
  }
];

export const CODING_CHALLENGES: CodingChallenge[] = [
  {
    id: 'code-1',
    title: 'Two Sum Problem',
    difficulty: 'Easy',
    category: 'Arrays & Hashing',
    description: 'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`. Each input has exactly one solution, and you may not use the same element twice.',
    inputFormat: 'nums = [2,7,11,15], target = 9',
    outputFormat: '[0, 1]',
    sampleInput: '[2, 7, 11, 15], target = 9',
    sampleOutput: '[0, 1]',
    starterCode: {
      python: 'def twoSum(nums, target):\n    # Write your O(n) hash map solution here\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []',
      java: 'class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int comp = target - nums[i];\n            if (map.containsKey(comp)) return new int[] { map.get(comp), i };\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}',
      javascript: 'function twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const comp = target - nums[i];\n    if (map.has(comp)) return [map.get(comp), i];\n    map.set(nums[i], i);\n  }\n  return [];\n}'
    },
    solutionExplanation: 'Use a Hash Map to store elements and their index in a single pass. For each element, lookup target - current in O(1) time.'
  },
  {
    id: 'code-2',
    title: 'Reverse a Linked List',
    difficulty: 'Easy',
    category: 'Linked Lists',
    description: 'Given the head of a singly linked list, reverse the list, and return the reversed list.',
    inputFormat: 'head = [1,2,3,4,5]',
    outputFormat: '[5,4,3,2,1]',
    sampleInput: '[1, 2, 3, 4, 5]',
    sampleOutput: '[5, 4, 3, 2, 1]',
    starterCode: {
      python: 'def reverseList(head):\n    prev = None\n    curr = head\n    while curr:\n        next_temp = curr.next\n        curr.next = prev\n        prev = curr\n        curr = next_temp\n    return prev',
      java: 'public ListNode reverseList(ListNode head) {\n    ListNode prev = null;\n    ListNode curr = head;\n    while (curr != null) {\n        ListNode next = curr.next;\n        curr.next = prev;\n        prev = curr;\n        curr = next;\n    }\n    return prev;\n}',
      javascript: 'function reverseList(head) {\n  let prev = null;\n  let curr = head;\n  while (curr) {\n    const next = curr.next;\n    curr.next = prev;\n    prev = curr;\n    curr = next;\n  }\n  return prev;\n}'
    },
    solutionExplanation: 'Iteratively adjust node pointers backwards while tracking next nodes in a temporary variable.'
  },
  {
    id: 'code-3',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    category: 'Sliding Window',
    description: 'Given a string `s`, find the length of the longest substring without duplicate characters.',
    inputFormat: 's = "abcabcbb"',
    outputFormat: '3 (Explanation: "abc")',
    sampleInput: '"abcabcbb"',
    sampleOutput: '3',
    starterCode: {
      python: 'def lengthOfLongestSubstring(s):\n    char_map = {}\n    left = 0\n    max_len = 0\n    for right, char in enumerate(s):\n        if char in char_map and char_map[char] >= left:\n            left = char_map[char] + 1\n        char_map[char] = right\n        max_len = max(max_len, right - left + 1)\n    return max_len',
      java: 'public int lengthOfLongestSubstring(String s) {\n    Map<Character, Integer> map = new HashMap<>();\n    int max = 0, left = 0;\n    for (int right = 0; right < s.length(); right++) {\n        char c = s.charAt(right);\n        if (map.containsKey(c) && map.get(c) >= left) {\n            left = map.get(c) + 1;\n        }\n        map.put(c, right);\n        max = Math.max(max, right - left + 1);\n    }\n    return max;\n}',
      javascript: 'function lengthOfLongestSubstring(s) {\n  const map = new Map();\n  let left = 0, max = 0;\n  for (let right = 0; right < s.length; right++) {\n    if (map.has(s[right]) && map.get(s[right]) >= left) {\n      left = map.get(s[right]) + 1;\n    }\n    map.set(s[right], right);\n    max = Math.max(max, right - left + 1);\n  }\n  return max;\n}'
    },
    solutionExplanation: 'Use a dynamic sliding window where the left boundary jumps forward to the index following any duplicate character.'
  }
];

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'iq-1',
    category: 'Technical',
    topic: 'DBMS',
    question: 'What is the difference between TRUNCATE, DROP, and DELETE in SQL?',
    answerSummary: 'DELETE is a DML command that removes specific rows (can be rolled back with WHERE). TRUNCATE is DDL that resets the entire table quickly (deallocates pages). DROP is DDL that deletes both table structure and data permanently.',
    keyPoints: [
      'DELETE generates rollback logs for each deleted row; TRUNCATE logs only page deallocations.',
      'TRUNCATE cannot have a WHERE clause; DELETE can.',
      'DROP removes the table schema from the data dictionary entirely.'
    ],
    commonMistakes: [
      'Saying TRUNCATE and DROP are the same thing.',
      'Claiming DELETE is faster than TRUNCATE (TRUNCATE is much faster).'
    ]
  },
  {
    id: 'iq-2',
    category: 'Technical',
    topic: 'Java & OOP',
    question: 'Explain why String is immutable in Java.',
    answerSummary: 'Strings in Java are immutable for String Constant Pool caching, thread safety, security (class loading & network URLs), and stable hash code computation for HashMap keys.',
    keyPoints: [
      'String Pool saves heap memory by reusing string literals.',
      'Immutability guarantees thread safety without synchronization overhead.',
      'Pre-computed hashCode allows fast Map lookups.'
    ],
    commonMistakes: [
      'Confusing String with StringBuilder or StringBuffer.',
      'Assuming String variables cannot be reassigned (the reference changes, not the underlying object).'
    ]
  },
  {
    id: 'iq-3',
    category: 'HR',
    topic: 'Self Introduction & Behavioral',
    question: 'Tell me about yourself (Opening HR Question).',
    answerSummary: 'Structure using the Present-Past-Future model: (1) Current academic & technical standing, (2) Key technical projects and achievements in college, (3) Why you are excited about this specific company and role.',
    keyPoints: [
      'Keep it strictly between 90 to 120 seconds.',
      'Highlight 2-3 core strengths relevant to the job description.',
      'Conclude with your passion for learning and engineering.'
    ],
    commonMistakes: [
      'Reciting your resume word-for-word without storytelling.',
      'Speaking too much about personal hobbies or family background instead of technical capabilities.'
    ]
  },
  {
    id: 'iq-4',
    category: 'HR',
    topic: 'Behavioral & Teamwork',
    question: 'Describe a situation where you had a conflict in a college team project. How did you resolve it?',
    answerSummary: 'Use the STAR method (Situation, Task, Action, Result). Focus on constructive communication, objective technical evaluation, and achieving project delivery deadlines.',
    keyPoints: [
      'Situation: Disagreement on tech stack or module workload.',
      'Action: Organised a code benchmark or balanced task allocation objectively.',
      'Result: Completed project on time with high marks and retained team goodwill.'
    ],
    commonMistakes: [
      'Blaming teammates or speaking negatively about peers.',
      'Claiming you have never had any conflicts.'
    ]
  }
];
